proxy_cache_path /tmp/nginx keys_zone=mycache:1m;


server {
    location / {
        #Proxy settings for Django server upstream
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /healthcheck {
        #This is for AWS To hit healthchecks
        add_header Content-Type text/plain;
        return 200 'Up and running!';
    }
    location /static/ {
        alias /staticfiles/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }
}