from django.contrib import admin
from django.utils.html import format_html
import json

from .models import LocationEvent, TransitEvent


# ---------------------------------------------------------
# LOCATION EVENT ADMIN
# ---------------------------------------------------------

@admin.register(LocationEvent)
class LocationEventAdmin(admin.ModelAdmin):
    list_display = (
        "id",
        "user",
        "event_type",
        "start_time",
        "end_time",
        "duration_seconds",
        "confidence",
        "radius_m",
        "avg_accuracy_m",
        "h3",
        "created_at",
    )

    list_filter = (
        "event_type",
        "user",
        "start_time",
        "end_time",
    )

    search_fields = (
        "user__id",
        "h3",
    )

    ordering = ("-start_time",)

    readonly_fields = (
        "user",
        "event_type",
        "start_time",
        "end_time",
        "duration_seconds",
        "h3",
        "center_lat",
        "center_lon",
        "confidence",
        "avg_accuracy_m",
        "radius_m",
        "features",
        "created_at",
        "pretty_features",
    )

    fieldsets = (
        ("Core", {
            "fields": (
                "user",
                "event_type",
                "confidence",
            )
        }),
        ("Time", {
            "fields": (
                "start_time",
                "end_time",
                "duration_seconds",
            )
        }),
        ("Location", {
            "fields": (
                "h3",
                "center_lat",
                "center_lon",
                "radius_m",
            )
        }),
        ("Accuracy", {
            "fields": (
                "avg_accuracy_m",
            )
        }),
        ("Debug / ML Features", {
            "fields": (
                "pretty_features",
            )
        }),
    )

    def pretty_features(self, obj):
        if not obj.features:
            return "-"

        return format_html(
            "<pre style='white-space: pre-wrap; font-size: 12px'>{}</pre>",
            json.dumps(obj.features, indent=2)
        )

    pretty_features.short_description = "Features"


    def has_add_permission(self, request):
        return False  # generated by pipeline only


# ---------------------------------------------------------
# TRANSIT EVENT ADMIN
# ---------------------------------------------------------

@admin.register(TransitEvent)
class TransitEventAdmin(admin.ModelAdmin):
    list_display = (
        "id",
        "user",
        "start_event",
        "end_event",
        "start_time",
        "end_time",
        "duration_seconds",
        "distance_meters",
        "speed_mps",
        "created_at",
    )

    list_filter = (
        "user",
        "start_time",
        "end_time",
    )

    search_fields = (
        "user__id",
        "start_h3",
        "end_h3",
    )

    ordering = ("-start_time",)

    readonly_fields = (
        "user",
        "start_event",
        "end_event",
        "start_h3",
        "end_h3",
        "start_time",
        "end_time",
        "duration_seconds",
        "distance_meters",
        "speed_mps",
        "metadata",
        "created_at",
        "pretty_metadata",
    )

    fieldsets = (
        ("Link", {
            "fields": (
                "user",
                "start_event",
                "end_event",
            )
        }),
        ("Time", {
            "fields": (
                "start_time",
                "end_time",
                "duration_seconds",
            )
        }),
        ("Movement", {
            "fields": (
                "distance_meters",
                "speed_mps",
                "start_h3",
                "end_h3",
            )
        }),
        ("Debug", {
            "fields": (
                "pretty_metadata",
            )
        }),
    )

    def pretty_metadata(self, obj):
        if not obj.metadata:
            return "-"

        return format_html(
            "<pre style='white-space: pre-wrap; font-size: 12px'>{}</pre>",
            json.dumps(obj.metadata, indent=2)
        )

    pretty_metadata.short_description = "Metadata"

    def has_add_permission(self, request):
        return False