# Generated by Django 6.0.4 on 2026-04-13 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('h3_r12', models.CharField(db_index=True, max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('confirmed', 'Confirmed'), ('processed', 'Processed'), ('discarded', 'Discarded')], db_index=True, default='candidate', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='locationping',
            name='accuracy_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationping',
            name='h3_r10',
            field=models.CharField(db_index=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationping',
            name='h3_r12',
            field=models.CharField(db_index=True, default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationping',
            name='h3_r13',
            field=models.CharField(db_index=True, default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationping',
            name='h3_r15',
            field=models.CharField(db_index=True, default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationping',
            name='h3_r8',
            field=models.CharField(db_index=True, default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationping',
            name='speed_mps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationping',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locationping',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['user', 'timestamp'], name='locations_l_user_id_995b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['h3_r12', 'timestamp'], name='locations_l_h3_r12_25f090_idx'),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['h3_r10', 'timestamp'], name='locations_l_h3_r10_1c6a66_idx'),
        ),
        migrations.AddField(
            model_name='stop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
