# Generated by Django 6.0.4 on 2026-04-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_stop_locationping_accuracy_m_locationping_h3_r10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationping',
            name='dedupe_hash',
            field=models.CharField(db_index=True, default='ddd', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
