# Generated by Django 6.0.4 on 2026-04-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_locationping_dedupe_hash'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='locationping',
            name='locations_l_user_id_995b2e_idx',
        ),
        migrations.RemoveIndex(
            model_name='locationping',
            name='locations_l_h3_r12_25f090_idx',
        ),
        migrations.RemoveIndex(
            model_name='locationping',
            name='locations_l_h3_r10_1c6a66_idx',
        ),
        migrations.DeleteModel(
            name='LocationPing',
        ),
    ]
