# Generated by Django 6.0.4 on 2026-04-13 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_locationping_locations_l_user_id_995b2e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('h3', models.CharField(db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('stop', 'Stop'), ('zone', 'Zone'), ('transit', 'Transit')], db_index=True, max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('confidence', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransitEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_h3', models.CharField(db_index=True, max_length=20)),
                ('end_h3', models.CharField(db_index=True, max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_seconds', models.IntegerField()),
                ('distance_in_meters', models.FloatField()),
                ('speed_in_meters_per_second', models.FloatField()),
                ('end_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transit', to='locations.locationevent')),
                ('start_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transit', to='locations.locationevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
        migrations.AddIndex(
            model_name='locationevent',
            index=models.Index(fields=['user', 'start_time'], name='locations_l_user_id_4771a3_idx'),
        ),
        migrations.AddIndex(
            model_name='locationevent',
            index=models.Index(fields=['user', 'event_type'], name='locations_l_user_id_4aa086_idx'),
        ),
    ]
