# Generated by Django 6.0.4 on 2026-04-14 18:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_locationevent_transitevent_delete_stop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='transitevent',
            old_name='distance_in_meters',
            new_name='distance_meters',
        ),
        migrations.RenameField(
            model_name='transitevent',
            old_name='speed_in_meters_per_second',
            new_name='speed_mps',
        ),
        migrations.AddField(
            model_name='locationevent',
            name='avg_accuracy_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationevent',
            name='avg_radius_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationevent',
            name='avg_speed_mps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationevent',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locationevent',
            name='spatial_entropy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transitevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transitevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='locationevent',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='locationevent',
            name='event_type',
            field=models.CharField(choices=[('stop', 'Stop'), ('zone', 'Zone')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='locationevent',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transitevent',
            name='end_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits_in', to='locations.locationevent'),
        ),
        migrations.AlterField(
            model_name='transitevent',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transitevent',
            name='start_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits_out', to='locations.locationevent'),
        ),
        migrations.AlterField(
            model_name='transitevent',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='locationevent',
            index=models.Index(fields=['user', 'end_time'], name='locations_l_user_id_9ae8f9_idx'),
        ),
        migrations.AddIndex(
            model_name='transitevent',
            index=models.Index(fields=['user', 'start_time'], name='locations_t_user_id_e7c18d_idx'),
        ),
        migrations.AddIndex(
            model_name='transitevent',
            index=models.Index(fields=['user', 'end_time'], name='locations_t_user_id_830cb2_idx'),
        ),
    ]
