# Generated by Django 6.0.4 on 2026-04-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_rename_distance_in_meters_transitevent_distance_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationevent',
            name='is_open',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
