# Generated by Django 6.0.4 on 2026-04-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_locationevent_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationevent',
            name='is_open',
        ),
        migrations.AddField(
            model_name='locationevent',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('discarded', 'Discarded')], db_index=True, default='open', max_length=20),
        ),
    ]
