# Generated by Django 6.0.4 on 2026-04-15 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_remove_locationevent_is_open_locationevent_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='locationevent',
            name='locations_l_user_id_9ae8f9_idx',
        ),
        migrations.RenameField(
            model_name='locationevent',
            old_name='metadata',
            new_name='features',
        ),
        migrations.AddField(
            model_name='locationevent',
            name='center_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationevent',
            name='center_lon',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationevent',
            name='radius_m',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationevent',
            name='avg_accuracy_m',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationevent',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='locationevent',
            name='duration_seconds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='locationevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='locationevent',
            index=models.Index(fields=['h3'], name='locations_l_h3_d47a1e_idx'),
        ),
        migrations.RemoveField(
            model_name='locationevent',
            name='avg_radius_m',
        ),
        migrations.RemoveField(
            model_name='locationevent',
            name='avg_speed_mps',
        ),
        migrations.RemoveField(
            model_name='locationevent',
            name='spatial_entropy',
        ),
        migrations.RemoveField(
            model_name='locationevent',
            name='status',
        ),
    ]
