name: 🚀 Deployment

on:
  push:
    branches: ["main"]

permissions:
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_LIGHTSAIL_SERVICE_NAME: perch-social

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    name: 🐳 Build & Push Images
    runs-on: ubuntu-latest

    steps:
      - name: 🗂 Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Install system tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: ☁️ Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 🏗 Build Django
        run: |
          docker build -t django:latest -f ./deployment/django/Dockerfile .

      - name: 🏗 Build Worker
        run: |
          docker build -t rqworker:latest -f ./deployment/rq-worker/Dockerfile .

      - name: 🏗 Build NGINX
        run: |
          docker build -t nginx:latest -f ./deployment/nginx/Dockerfile .

      - name: 📦 Push Django
        run: |
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }} \
            --label django \
            --image django:latest

      - name: 📦 Push Worker
        run: |
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }} \
            --label rqworker \
            --image rqworker:latest

      - name: 📦 Push NGINX
        run: |
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }} \
            --label nginx \
            --image nginx:latest

      - name: 🚀 Deploy
        run: |
          aws lightsail create-container-service-deployment \
            --service-name ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }} \
            --containers file://deployment/AWS/deploymentconfig.json \
            --public-endpoint file://deployment/AWS/publicendpoint.json