name: 🚀 Deployment

on:
  push:
    branches: ["main"]

permissions:
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_LIGHTSAIL_SERVICE_NAME: perch-social

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true


jobs:
  deploy:
    name: 🚀 Build & Deploy All Services
    runs-on: ubuntu-latest

    steps:
      - name: 🗂 Checkout code
        uses: actions/checkout@v4
      - name: 🤐 Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_REDIS_HOST: ${{ secrets.REDIS_HOST }}
          envkey_REDIS_USER: ${{ secrets.REDIS_USER }}
          envkey_REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          envkey_DEBUG: false
          directory: core
          file_name: .env
          fail_on_empty: false

      - name: ⚙️ Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: ☁️ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 🏢 Install Lightsail CLI
        run: |
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o lightsailctl
          sudo mv lightsailctl /usr/local/bin/lightsailctl
          sudo chmod +x /usr/local/bin/lightsailctl
          lightsailctl --version

      - name: 🐳 Build Django image
        run: |
          docker build -t django:latest -f ./deployment/django/Dockerfile .

      - name: 🐳 Build Worker image
        run: |
          docker build -t rqworker:latest -f ./deployment/rq-worker/Dockerfile .

      - name: 🐳 Build Scheduler image
        run: |
          docker build -t rqscheduler:latest -f ./deployment/rq-scheduler/Dockerfile .


      - name: 🐳 Build NGINX image
        run: |
          docker build -t nginx:latest -f ./deployment/nginx/Dockerfile .

      - name: 📦 Push Django image
        run: |
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }} \
            --label django \
            --image django:latest

      - name: 📦 Push Worker image
        run: |
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }} \
            --label rqworker \
            --image rqworker:latest

      - name: 📦 Push Scheduler image
        run: |
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }} \
            --label rqscheduler \
            --image rqscheduler:latest

      - name: 📦 Push NGINX image
        run: |
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }} \
            --label nginx \
            --image nginx:latest

      - name: 🚀 Deploy to Lightsail
        run: |
          aws lightsail create-container-service-deployment \
            --service-name ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }} \
            --containers file://deployment/AWS/deploymentconfig.json \
            --public-endpoint file://deployment/AWS/publicendpoint.json
      - name: 🗑️ Delete old container images
        run: python deployment/AWS/clear_old_images.py